# Generated by Django 4.2.3 on 2023-07-17 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=128, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nome do produto, não deve ser nulo'),
        ),
    ]
