# Generated by Django 4.2.3 on 2023-08-12 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_produto_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'managed': True, 'ordering': ['criado_em'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AddField(
            model_name='produto',
            name='criado_em',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 12, 23, 38, 25, 862433, tzinfo=datetime.timezone.utc), null=True, verbose_name='Criado em'),
        ),
    ]
